[tool.poetry]
name = "django4exam"
version = "0.1.0"
description = ""
authors = ["neo <neo@koreanbar.or.kr>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "<5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
